#!/usr/bin/env bash
#script manages manage_my_process

#when passing start
#	starts manages the processes
#	create a file countaine PID (/var/run/my_process.pid)
#	displays that the file started

# when passing stop
#	stop manages the processes
#	delete the file countaine PID
#	display that the processes stoped

# when passing restart
#       stop manages the processes
#       delete the file countaine PID /var/run/my_process.pid
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#       display that the processe restarted

#when no argument is passed or any other passed
#	Displays Usage: manage_my_process {start|stop|restart}

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
