#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#  stopped our 4-to_infinity_and_beyond process using ctrl+c
# use kill

ID = $(pgrep "bash ./4-to_infinity_and_beyond" -f)

if [ -n "$ID" ]
then
	kill -15 "$ID"
fi
