#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#  stopped our 4-to_infinity_and_beyond process using ctrl+c
# use kill

id = $(pgrep "bash ./4-to_infinity_and_beyond" -f)

if [ -n "$id" ]
then
	kill -15 "$id"
fi
