#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#  stopped our 4-to_infinity_and_beyond process using ctrl+c
# use kill

#the pid of the prgrm
pid=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

if [ -n "$pid" ]
then
	kill -15 "$pid"
fi
