#!/usr/bin/env bash
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
#a copy of 6-stop_me_if_you_can that kill this file

trap 'echo "I am invincible!!!"' 15
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
