#!/usr/bin/env bash
#fizzbazz

for iter in {1..100}
do
	if (( iter % 3 == 0 ))
	then
		echo "Fizz"
	elif (( iter % 5 == 0 ))
	then
		echo "Buzz"
	elif (( iter % 15 == 0 ))
	then
		echo "FizzBuzz"
	else
		echo "$iter"
	fi
done
