#!/usr/bin/env bash
#make up story based on /etc/passwd file

while IFS=':' read -r usr pw idusr idgrp inf dirh shell;
do
	echo "The user $usr is part of the $idgrp gang,"\
	"lives in $dirh and rides $shell."\
	"$idusr's place is protected by the passcode $pw,"\
	"more info about the user here: $inf"
done < "/etc/passwd"
