#!/usr/bin/env bash
#iteriting 10 times using while
#bad luck from China for the 4 iter
#bad luck from Japan for the 9 iter
#bad luck from Italy for the 17 iter
#iter integer for the rest

iter=1
while [ $iter -le 20 ]
do
	echo "$iter"
	case $iter in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	iter=$((iter + 1))
done
